### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by IsobelGuthrie** [sraorao/snakemake_GMS_MT2022#1]
/bin/bash: activate: No such file or directory
/bin/bash: activate: No such file or directory
/bin/bash: Rscript: command not found
Error in job plot_dupmetrics while creating output file output/plots/dups.pdf.
RuleException:
CalledProcessError in line 65 of /home/iegut/snakemake_GMS_MT2022/session2/Snakefile:
Command 'Rscript /home/iegut/snakemake_GMS_MT2022/session2/scripts/.snakemake.invzlaef.plot.R' returned non-zero exit status 127.
  File "/home/iegut/snakemake_GMS_MT2022/session2/Snakefile", line 65, in __rule_plot_dupmetrics
  File "/home/iegut/miniconda3/envs/snakemake_GMS/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Traceback (most recent call last):
  File "/home/iegut/snakemake_GMS_MT2022/session2/scripts/.snakemake.2czmw33n.plot.py", line 12, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Error in job plot_dupmetrics_python while creating output file output/plots/dups_python.pdf.
RuleException:
CalledProcessError in line 71 of /home/iegut/snakemake_GMS_MT2022/session2/Snakefile:
Command 'python /home/iegut/snakemake_GMS_MT2022/session2/scripts/.snakemake.2czmw33n.plot.py' returned non-zero exit status 1.
  File "/home/iegut/snakemake_GMS_MT2022/session2/Snakefile", line 71, in __rule_plot_dupmetrics_python
  File "/home/iegut/miniconda3/envs/snakemake_GMS/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
finished with errors

**Comment by sraorao** [comment]
Thanks Isobel. This looks like a conda environment issue, could you 1) check that your conda is updated to latest version (you can do it with `mamba update -n base conda` 2) post your snakemake version 3) have a look at [this issue](https://github.com/snakemake/snakemake/issues/345) some of those solutions may be relevant - particularly, please check where python is located (`which python`) and whether you have multiple installations of python..?

BW
Rao

**Comment by mennowitteveen** [comment]
Hi, I encountered a similar issue on a recent snakemake version (8.16.0). I think that in several cases it has something to do with the initialization of the bash environment. It seems that my .bashrc does not get executed and hence the proper conda (a ~/miniconda3/) does not get activated and some old conda (located in /usr/bin/ which I have no influence over) gets used, which does not have an "activate" command in the associated path.
